gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"

gText_Gorz_Welcome::
	.string "Hold up! Some important info from\n"
	.string "this hack's creator\p"
	.string "Welcome to Pokémon Emerald: Classic!\p"
	.string "At its core, this is a difficulty\n"
	.string "hack with updated and new mechanics.\p"
	.string "This hack has built-in level caps\n"
    .string "based on which badges you have.\p"
    .string "If a Pokémon reaches the level cap,\n"
    .string "it'll only get 1 exp per KO until\l"
	.string "you earn the next badge.\p"
	.string "Also, many quality of life changes\n"
	.string "and tons of Pokémon variety.\p"
	.string "You can build your team using almost\n"
	.string "any Pokémon from the first eight\l"
	.string "generations!\p"
	.string "Before you get started, you'll need\n"
	.string "to choose a difficulty setting.\p"
	.string "Currently you can choose between\n"
	.string "Normal or Hard Mode.\p"
	.string "These options can be changed any\n"
	.string "time by pressing L in the game.\p"
	.string "Please select a mode to learn more\n"
	.string "about it.$"

gText_Gorz_NormalMode::
	.string "In Normal Mode, Trainers won't have\n"
	.string "EVs, so you won't need to worry\l"
	.string "about your own Pokémon's stats.\p"
	.string "This difficulty is recommended if\n"
	.string "you're new to difficulty hacks, or\l"
	.string "if you don't want to deal with EVs.\p"
	.string "So, would you like to play on\n"
	.string "Normal Mode?$"

gText_Gorz_HardMode::
	.string "In Hard Mode, Trainers will have EV-\n"
	.string "trained Pokémon, so you might\l"
	.string "want to EV train your own team.\p"
	.string "This difficulty is recommended for\n"
	.string "experienced players.\p"
	.string "So, would you like to play on\n"
	.string "Hard Mode?$"

gText_Gorz_ImpossibleMode::
	.string "Like Hard Mode, Trainers in Impossible\n"
	.string "Mode have EV trained teams.\p"
	.string "Healing and boosting moves\n"
	.string "and abilities are entirely disabled\p"
	.string "I'm not sure if this is even\n"
	.string "beatable to be honest!\p"
	.string "This difficulty is only recommended if\n"
	.string "it sounds appealing to you!\p"
	.string "So, would you like to play on\n"
	.string "Impossible Mode?$"

gText_Gorz_WhichDifficulty::
	.string "Which difficulty would you like to\n"
	.string "play on?$"

gText_Gorz_GrindingModes::
    .string "Great! Now, there's one last thing\n"
    .string "to decide. Minimum grinding mode.\p"
    .string "If enabled, this option will give\n"
	.string "all found Pokémon 31 IVs in each stat.\p"
	.string "It's recommended to use this setting\n"
	.string "as most trainers have hand-picked IVs.\p"
	.string "Now, what setting would\n"
	.string "you like to play on?$"

gText_Gorz_WhichGrindingMode::
	.string "What grinding setting would\n"
	.string "you like to play on?$"	

gText_Gorz_DefaultGrinding::
	.string "All found Pokémon will have \n"
	.string "random IVs. Is this okay?$"

gText_Gorz_MinGrinding::
	.string "All found Pokémon will have 31\n"
	.string "IVs in every stat. Is this okay?$"

gText_Gorz_Documents::
	.string "If you want more information,\n"
	.string "check the documents that came\l"
	.string "with the hack's patch.\p"
	.string "They cover everything from Pokémon and\n"
	.string "battle changes to new move effects.\p"
	.string "Good luck, I hope you enjoy the hack!\n"
	.string "- Tony\p"
	.string "$"
