Route102_EventScript_ItemPotion::
	finditem ITEM_POTION
	end

Route103_EventScript_ItemTM81::
	finditem ITEM_TM81
	end

Route103_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route104_EventScript_ItemCharizarditeX::
	finditem ITEM_CHARIZARDITE_X
	end

Route104_EventScript_ItemTM10::
	finditem ITEM_TM10
	end

Route104_EventScript_ItemTM09:: @StruggleBug
	finditem ITEM_TM77
	end

Route104_EventScript_ItemSootheBell::
	finditem ITEM_SOOTHE_BELL
	end

Route105_EventScript_ItemSwampertite::
	finditem ITEM_SWAMPERTITE
	end

Route105_EventScript_ItemTM55::
	finditem ITEM_TM55
	end	

Route106_EventScript_ItemTM03:: @Water Pulse
	finditem ITEM_TM03
	end

Route108_EventScript_ItemBlastoisinite::
	finditem ITEM_BLASTOISINITE
	end

Route109_EventScript_ItemTM98::
	finditem ITEM_TM98
	end

Route109_EventScript_ItemBottleCap::
	finditem ITEM_BOTTLE_CAP
	end

Route110_EventScript_ItemZapPlate::
	finditem ITEM_ZAP_PLATE
	end

Route110_EventScript_ItemTM51::
	finditem ITEM_TM51
	end

Route110_EventScript_ItemElixir::
	finditem ITEM_ELIXIR
	end

Route111_EventScript_ItemTM37::
	finditem ITEM_TM37
	end

Route111_EventScript_ItemStardust::
	finditem ITEM_STARDUST
	end

Route111_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route111_EventScript_ItemElixir::
	finditem ITEM_BOTTLE_CAP
	end

Route112_EventScript_ItemNugget::
	finditem ITEM_BOTTLE_CAP
	end

Route113_EventScript_ItemMaxEther::
	finditem ITEM_MAX_ETHER
	end

Route113_EventScript_ItemTM91::
	finditem ITEM_TM91
	end

Route113_EventScript_ItemDreamBall::
	finditem ITEM_DREAM_BALL
	end

Route114_EventScript_ItemRareCandy::
	finditem ITEM_BIG_NUGGET
	end

Route114_EventScript_ItemProtein::
	finditem ITEM_BOTTLE_CAP
	end

Route114_EventScript_ItemEnergyPowder::
	finditem ITEM_ENERGY_POWDER
	end

Route115_EventScript_ItemSoftSand::
	finditem ITEM_SOFT_SAND
	end

Route115_EventScript_ItemTM01::
	finditem ITEM_TM01
	end

Route115_EventScript_ItemCharizarditeY::
	finditem ITEM_CHARIZARDITE_Y
	end

Route115_EventScript_ItemDragonFang::
	finditem ITEM_DRAGON_FANG
	end

Route115_EventScript_ItemHealPowder::
	finditem ITEM_HEAL_POWDER
	end

Route115_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

Route116_EventScript_ItemMoonStone::
	finditem ITEM_MOON_STONE
	end

Route116_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

Route116_EventScript_ItemRepel::
	finditem ITEM_BOTTLE_CAP
	end

Route116_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

Route116_EventScript_ItemTM67::
	finditem ITEM_TM67
	end

Route117_EventScript_ItemDreamBall::
	finditem ITEM_DREAM_BALL, 3
	end

Route117_EventScript_ItemElectricSeed::
	finditem ITEM_ELECTRIC_SEED
	end

Route118_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route119_EventScript_ItemGrassySeed::
	finditem ITEM_GRASSY_SEED
	end

Route119_EventScript_ItemTM22::
	finditem ITEM_TM22
	end

Route119_EventScript_ItemElixir::
	finditem ITEM_PP_UP
	end

Route119_EventScript_ItemSceptilite::
	finditem ITEM_SCEPTILITE
	end

Route119_EventScript_ItemGoldBottleCap::
	finditem ITEM_GOLD_BOTTLE_CAP
	end

Route119_EventScript_ItemWhiteHerb::
	finditem ITEM_WHITE_HERB
	end

Route119_EventScript_ItemGrassGem::
	finditem ITEM_GRASS_GEM
	end

Route119_EventScript_ItemElixir2::
	finditem ITEM_PP_UP
	end

Route120_EventScript_ItemNugget::
	finditem ITEM_BOTTLE_CAP
	end

Route120_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

Route120_EventScript_ItemHyperPotion::
	finditem ITEM_HYPER_POTION
	end

Route120_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL, 3
	end

Route120_EventScript_ItemRevive::
	finditem ITEM_REVIVE
	end

Route121_EventScript_ItemTM53EnergyBall::
	finditem ITEM_TM_ENERGY_BALL
	end

Route121_EventScript_ItemBeedrillite::
	finditem ITEM_BEEDRILLITE
	end	

Route121_EventScript_ItemMeadowPlate::
	finditem ITEM_MEADOW_PLATE
	end

Route121_EventScript_ItemPowerBracer::
	finditem ITEM_POWER_BRACER
	end

Route123_EventScript_ItemTM56::
	finditem ITEM_TM56
	end

Route123_EventScript_ItemUltraBall::
	finditem ITEM_ULTRA_BALL
	end

Route123_EventScript_ItemLeek::
	finditem ITEM_LEEK
	end

Route123_EventScript_ItemPPUp::
	finditem ITEM_PP_MAX
	end

Route123_EventScript_ItemLopunnite::
	finditem ITEM_LOPUNNITE
	end

Route124_EventScript_ItemRedShard::
	finditem ITEM_RED_SHARD
	end

Route124_EventScript_ItemBlueShard::
	finditem ITEM_BLUE_SHARD
	end

Route124_EventScript_ItemYellowShard::
	finditem ITEM_YELLOW_SHARD
	end

Route125_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route126_EventScript_ItemGreenShard::
	finditem ITEM_GREEN_SHARD
	end

Route127_EventScript_ItemZinc::
	finditem ITEM_ZINC
	end

Route127_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route127_EventScript_ItemRareCandy::
	finditem ITEM_NUGGET
	end

Route132_EventScript_ItemRareCandy::
	finditem ITEM_NUGGET
	end

Route132_EventScript_ItemProtein::
	finditem ITEM_PROTEIN
	end

Route133_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

Route133_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

Route133_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

Route134_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

Route134_EventScript_ItemStarPiece::
	finditem ITEM_STAR_PIECE
	end

PetalburgCity_EventScript_ItemBottleCap::
	finditem ITEM_BOTTLE_CAP
	end

PetalburgCity_EventScript_ItemVenusaurite:: @ 82910C1
	finditem ITEM_VENUSAURITE
	end

MauvilleCity_EventScript_ItemXSpeed::
	finditem ITEM_X_SPEED
	end

RustboroCity_EventScript_ItemBottleCap::
	finditem ITEM_BOTTLE_CAP
	end

LilycoveCity_EventScript_ItemMaxRepel::
	finditem ITEM_MAX_REPEL
	end

MossdeepCity_EventScript_ItemNetBall::
	finditem ITEM_NET_BALL
	end

PetalburgWoods_EventScript_ItemXAttack::
	finditem ITEM_LEAF_STONE
	end

PetalburgWoods_EventScript_ItemGreatBall::
	finditem ITEM_NET_BALL, 3
	end

PetalburgWoods_EventScript_ItemEther::
	finditem ITEM_ETHER
	end

PetalburgWoods_EventScript_ItemInsectPlate::
	finditem ITEM_INSECT_PLATE
	end

RusturfTunnel_EventScript_ItemPokeBall::
	finditem ITEM_FRIEND_BALL, 3
	end

RusturfTunnel_EventScript_ItemTM63::
	finditem ITEM_TM63
	end

GraniteCave_1F_EventScript_ItemEscapeRope::
	finditem ITEM_BOTTLE_CAP
	end

GraniteCave_B1F_EventScript_ItemPokeBall::
	finditem ITEM_DREAM_BALL
	end

GraniteCave_B2F_EventScript_ItemMawilite::
	finditem ITEM_MAWILITE
	end

GraniteCave_B2F_EventScript_ItemIronBall::
	finditem ITEM_IRON_BALL
	end

JaggedPass_EventScript_ItemTM11::
	finditem ITEM_TM11
	end

FieryPath_EventScript_ItemFireStone::
	finditem ITEM_BLAZIKENITE
	end

FieryPath_EventScript_ItemTM06::
	finditem ITEM_TM06
	end

MeteorFalls_1F_1R_EventScript_ItemTM23::
	finditem ITEM_TM23
	end

MeteorFalls_1F_1R_EventScript_ItemFullHeal::
	finditem ITEM_BOTTLE_CAP
	end

MeteorFalls_1F_1R_EventScript_ItemTM82::
	finditem ITEM_TM82
	end

MeteorFalls_1F_1R_EventScript_ItemPPUP::
	finditem ITEM_PP_UP
	end

MeteorFalls_B1F_2R_EventScript_ItemTM02::
	finditem ITEM_TM02
	end

NewMauville_Inside_EventScript_ItemManectite::
	finditem ITEM_MANECTITE
	end

NewMauville_Inside_EventScript_ItemEscapeRope::
	finditem ITEM_ELECTRIC_SEED
	end

NewMauville_Inside_EventScript_ItemThunderStone::
	finditem ITEM_THUNDER_STONE
	end

NewMauville_Inside_EventScript_ItemFullHeal::
	finditem ITEM_ELECTIRIZER
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal::
	finditem ITEM_ELECTRIC_GEM
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

AbandonedShip_Rooms_B1F_EventScript_ItemSeaIncense::
	finditem ITEM_SEA_INCENSE
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall::
	finditem ITEM_DIVE_BALL
	end

AbandonedShip_Room_B1F_EventScript_ItemTM13::
	finditem ITEM_TM13
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRoomService::
	finditem ITEM_ROOM_SERVICE
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
	finditem ITEM_STORAGE_KEY
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemSharpedonite::
	finditem ITEM_SHARPEDONITE
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
	finditem ITEM_SCANNER
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM79::
	finditem ITEM_TM79
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTM18::
	finditem ITEM_TM18
	end

ScorchedSlab_EventScript_ItemTM64::
	finditem ITEM_TM64
	end

SafariZone_Northwest_EventScript_ItemTM86::
	finditem ITEM_TM86
	end

SafariZone_North_EventScript_ItemCalcium::
	finditem ITEM_CALCIUM
	end

SafariZone_Southwest_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

SafariZone_Northeast_EventScript_ItemNugget::
	finditem ITEM_NUGGET
	end

SafariZone_Southeast_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

MtPyre_2F_EventScript_ItemSpookyPlate::
	finditem ITEM_SPOOKY_PLATE
	end

MtPyre_3F_EventScript_ItemSuperRepel::
	finditem ITEM_SUPER_REPEL
	end

MtPyre_4F_EventScript_ItemSeaIncense::
	finditem ITEM_SEA_INCENSE
	end

MtPyre_5F_EventScript_ItemLaxIncense::
	finditem ITEM_LAX_INCENSE
	end

MtPyre_6F_EventScript_ItemTM30::
	finditem ITEM_TM30
	end

MtPyre_Exterior_EventScript_ItemMaxPotion::
	finditem ITEM_MAX_POTION
	end

MtPyre_Exterior_EventScript_ItemTM48::
	finditem ITEM_TM48
	end

MtPyre_Summit_EventScript_ItemBanettite::
	giveitem ITEM_BANETTITE
	end

AquaHideout_B1F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL
	end

AquaHideout_B1F_EventScript_ItemNugget::
	finditem ITEM_BOTTLE_CAP
	end

AquaHideout_B1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

AquaHideout_B2F_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

AquaHideout_B2F_EventScript_ItemMasterBall::
	finditem ITEM_MASTER_BALL      // Unused
	end

Route119_EventScript_ItemBigNugget::
	finditem ITEM_BIG_NUGGET
	end

Route119_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

Route119_EventScript_ItemNestBall::
	finditem ITEM_NEST_BALL
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
	finditem ITEM_BIG_PEARL
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
	finditem ITEM_NUGGET
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
	finditem ITEM_ICE_HEAL
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTM07::
	finditem ITEM_TM07
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
	finditem ITEM_NEVER_MELT_ICE
	end

SeafloorCavern_Room9_EventScript_ItemTM26::
	finditem ITEM_TM26
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
	finditem ITEM_ORANGE_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
	finditem ITEM_HARBOR_MAIL
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
	finditem ITEM_WAVE_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
	finditem ITEM_SHADOW_MAIL
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
	finditem ITEM_WOOD_MAIL
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
	finditem ITEM_MECH_MAIL
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
	finditem ITEM_GLITTER_MAIL
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
	finditem ITEM_TROPIC_MAIL
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
	finditem ITEM_BEAD_MAIL
	end

VictoryRoad_1F_EventScript_ItemMaxElixir::
	finditem ITEM_MAX_ELIXIR
	end

VictoryRoad_1F_EventScript_ItemPPUp::
	finditem ITEM_PP_UP
	end

VictoryRoad_B1F_EventScript_ItemTM29::
	finditem ITEM_TM29
	end

VictoryRoad_B1F_EventScript_ItemFullRestore::
	finditem ITEM_FULL_RESTORE
	end

VictoryRoad_B2F_EventScript_ItemFullHeal::
	finditem ITEM_FULL_HEAL
	end

ArtisanCave_B1F_EventScript_ItemHPUp::
	finditem ITEM_HP_UP
	end

ArtisanCave_1F_EventScript_ItemCarbos::
	finditem ITEM_CARBOS
	end

MagmaHideout_1F_EventScript_ItemRareCandy::
	finditem ITEM_BOTTLE_CAP
	end

MagmaHideout_2F_2R_EventScript_ItemTM83::
	finditem ITEM_TM83
	end

MagmaHideout_2F_2R_EventScript_ItemTerrainExtender::
	finditem ITEM_TERRAIN_EXTENDER
	end

MagmaHideout_3F_1R_EventScript_ItemNugget::
	finditem ITEM_BOTTLE_CAP
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax::
	finditem ITEM_PP_MAX
	end

MagmaHideout_4F_EventScript_ItemMaxRevive::
	finditem ITEM_MAX_REVIVE
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
	finditem ITEM_STARDUST
	end

RustboroCity_DevonCorp_2F_EventScript_ItemTM61::
	finditem ITEM_TM61
	end

GraniteCave_B2F_EventScript_ItemTM28::
	finditem ITEM_TM28
	end

DewfordGardens_EventScript_ItemTM78::
	finditem ITEM_TM78
	end

Route110_EventScript_ItemTM73::
	finditem ITEM_TM73
	end

Route117_EventScript_ItemMetronome::
	finditem ITEM_METRONOME
	end

Route111_EventScript_ItemAbsolite::
	finditem ITEM_ABSOLITE
	end

MirageTower_2F_EventScript_ItemTM33::
	finditem ITEM_TM33
	end

Route120_EventScript_Item_Pidgeotite::
	finditem ITEM_PIDGEOTITE
	end

Common_EventScript_FindItem::
	callnative GetItemBallIdAndAmountFromTemplate
	finditem VAR_RESULT VAR_0x8009
	end
